# Generated by Django 4.2.1 on 2023-05-17 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcommerceStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('discovery_url', models.CharField(max_length=100, unique=True)),
                ('api_url', models.URLField(blank=True, max_length=255)),
                ('package_name', models.CharField(blank=True, max_length=50)),
                ('module_name', models.CharField(blank=True, max_length=50)),
                ('class_name', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ACTIVE', 'Picked Up'), ('FAILED', 'Extended'), ('FINISHED', 'Finished')], default='CREATED', max_length=10)),
                ('type', models.CharField(choices=[('STORES-CRAWL', 'Local Stores Crawl'), ('CATEGORIES-CRAWL', 'Categories Crawl'), ('PRODUCTS-CRAWL', 'Products Crawl'), ('PRODUCT-SCRAPE', 'Products Scrape'), ('PRODUCTLOCALDATA-SCRAPE', 'Product Local Data Scrape')], max_length=40)),
                ('category_level', models.IntegerField(blank=True, null=True)),
                ('created', models.IntegerField()),
                ('started_at', models.IntegerField(blank=True, null=True)),
                ('finished_at', models.IntegerField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='objects.ecommercestore')),
            ],
        ),
        migrations.CreateModel(
            name='LocalStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField(blank=True, max_length=255)),
                ('api_url', models.URLField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('parrent_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.ecommercestore')),
            ],
        ),
    ]
