"""
Used for local testing.
"""
import time
from scraper.stores.leroy_merlin.leroy_merlin import LeroyMerlinScraper
url_2 = [
{'url': 'https://www.leroymerlin.pl/materialy-budowlane,a132.html', 'name': 'Materiały budowlane', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/izolacja-budynkow,a141.html', 'name': 'Izolacja budynków', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/dachy-i-akcesoria,a143.html', 'name': 'Dachy i akcesoria', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/ogrzewanie,a2022.html', 'name': 'Ogrzewanie', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/konstrukcje-drewniane-i-metalowe,a148.html', 'name': 'Konstrukcje drewniane i metalowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/materialy-wykonczeniowe,a150.html', 'name': 'Materiały wykończeniowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/okna-i-drzwi,a138.html', 'name': 'Okna i drzwi', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/ogrodzenia-i-bramy,a152.html', 'name': 'Ogrodzenia i bramy', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/narzedzia-budowlane,a154.html', 'name': 'Narzędzia budowlane', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/hydraulika,a153.html', 'name': 'Hydraulika', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/elektronarzedzia,a103.html', 'name': 'Elektronarzędzia', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/narzedzia-reczne,a104.html', 'name': 'Narzędzia ręczne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/warsztat,a105.html', 'name': 'Warsztat', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/odziez-i-artykuly-bhp,a3134.html', 'name': 'Odzież i artykuły BHP', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/hydraulika,a107.html', 'name': 'Hydraulika', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/ogrzewanie,a110.html', 'name': 'Ogrzewanie', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/klimatyzacja-i-wentylacja,a111.html', 'name': 'Klimatyzacja i wentylacja', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/elektrycznosc,a114.html', 'name': 'Elektryczność', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/artykuly-metalowe,a117.html', 'name': 'Artykuły metalowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/zabezpieczenie-domu,a119.html', 'name': 'Zabezpieczenie domu', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/farby-lakiery-i-kleje,a120.html', 'name': 'Farby, lakiery i kleje', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/artykuly-gospodarcze,a121.html', 'name': 'Artykuły gospodarcze', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/drzwi-klamki-i-schody,a126.html', 'name': 'Drzwi, klamki i schody', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/podlogi-drewniane-panele-scienne,a184.html', 'name': 'Podłogi drewniane, Panele ścienne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/plytki-ceramiczne-na-sciane-i-podloge,a226.html', 'name': 'Płytki ceramiczne na ścianę i podłogę', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/kuchnie,a636.html', 'name': 'Kuchnie', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/akcesoria-kuchenne,a3491.html', 'name': 'Akcesoria kuchenne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/jadalnia,a3492.html', 'name': 'Jadalnia', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/meble-lazienkowe-i-lustra,a525.html', 'name': 'Meble łazienkowe i lustra', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/ceramika-lazienkowa,a540.html', 'name': 'Ceramika łazienkowa', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/wanny-i-kabiny-prysznicowe,a2106.html', 'name': 'Wanny i kabiny prysznicowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/armatura-lazienkowa,a590.html', 'name': 'Armatura łazienkowa', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/wyposazenie-lazienki,a604.html', 'name': 'Wyposażenie łazienki', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/akcesoria-lazienkowe,a2092.html', 'name': 'Akcesoria łazienkowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/garderoba-i-wnetrze,a724.html', 'name': 'Garderoba i wnętrze', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/elementy-mebli-i-okucia,a834.html', 'name': 'Elementy mebli i okucia', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/kominki,a894.html', 'name': 'Kominki', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/farby,a737.html', 'name': 'Farby', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/dekoracja-scian-sufitow-i-innych-powierzchni,a863.html', 'name': 'Dekoracja ścian, sufitów i innych powierzchni', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/dekoracja-okien,a924.html', 'name': 'Dekoracja okien', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/oswietlenie,a953.html', 'name': 'Oświetlenie', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/dywany-i-wykladziny,a1210.html', 'name': 'Dywany i wykładziny', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/dekoracja-wnetrz,a1234.html', 'name': 'Dekoracja wnętrz', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/ramki-obrazy-lustra,a1292.html', 'name': 'Ramki, obrazy, lustra', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/atelier-artystyczne,a1306.html', 'name': 'Atelier artystyczne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/organizacja-miejsca-pracy,a2490.html', 'name': 'Organizacja miejsca pracy', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/maszyny-ogrodnicze,a19.html', 'name': 'Maszyny ogrodnicze', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/porzadki-w-ogrodzie,a20.html', 'name': 'Porządki w ogrodzie', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/narzedzia-ogrodnicze,a21.html', 'name': 'Narzędzia ogrodnicze', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/nawadnianie,a23.html', 'name': 'Nawadnianie', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/relaks-w-ogrodzie,a22.html', 'name': 'Relaks w ogrodzie', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/architektura-ogrodowa,a24.html', 'name': 'Architektura ogrodowa', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/oswietlenie-doniczki-i-dekoracje,a25.html', 'name': 'Oświetlenie, doniczki i dekoracje', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/balkon-i-taras,a2368.html', 'name': 'Balkon i taras', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/rosliny-nasiona-cebule,a26.html', 'name': 'Rośliny, nasiona, cebule', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/uprawa-i-ochrona-roslin,a27.html', 'name': 'Uprawa i ochrona roślin', 'has_childs': True, 'has_products': False},
]

url_3 = [
{'url': 'https://www.leroymerlin.pl/materialy-budowlane/materialy-budowlane-stan-surowy,a156.html', 'name': 'Materiały budowlane - stan surowy', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/materialy-budowlane/zaprawy-i-tynki,a157.html', 'name': 'Zaprawy i tynki', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/materialy-budowlane/grunty-i-impregnaty,a160.html', 'name': 'Grunty i impregnaty', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/materialy-budowlane/kleje-i-zaprawy-klejowe,a163.html', 'name': 'Kleje i zaprawy klejowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/izolacja-budynkow/welna-mineralna-styropian-izolacja-akustyczna,a167.html', 'name': 'Wełna mineralna, styropian, izolacja akustyczna', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/izolacja-budynkow/kleje-uszczelniacze-izolacje,a395.html', 'name': 'Kleje, uszczelniacze, izolacje', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/dachy-i-akcesoria/pokrycia-dachowe,a196.html', 'name': 'Pokrycia dachowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/dachy-i-akcesoria/odprowadzanie-wody-deszczowej-z-dachu,a199.html', 'name': 'Odprowadzanie wody deszczowej z dachu', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/dachy-i-akcesoria/farby-i-uszczelniacze-dachowe,a203.html', 'name': 'Farby i uszczelniacze dachowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/ogrzewanie/kominy-i-odprowadzanie-spalin,a2031.html', 'name': 'Kominy i odprowadzanie spalin', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/ogrzewanie/kotly-piece-ogrzewanie-solarne,a2038.html', 'name': 'Kotły, piece, ogrzewanie solarne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/ogrzewanie/ogrzewanie-podlogowe,a2061.html', 'name': 'Ogrzewanie podłogowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/ogrzewanie/ogrzewanie-przenosne,a2098.html', 'name': 'Ogrzewanie przenośne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/ogrzewanie/akcesoria-do-piecow,a2064.html', 'name': 'Akcesoria do pieców', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/ogrzewanie/grzejniki-i-akcesoria,a2070.html', 'name': 'Grzejniki i akcesoria', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/konstrukcje-drewniane-i-metalowe/deski-plyty-wykonczeniowe-listwy,a206.html', 'name': 'Deski, płyty wykończeniowe, listwy', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/konstrukcje-drewniane-i-metalowe/prety-i-profile-metalowe,a208.html', 'name': 'Pręty i profile metalowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/konstrukcje-drewniane-i-metalowe/okucia-i-mocowania,a210.html', 'name': 'Okucia i mocowania', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/materialy-wykonczeniowe/elewacje,a215.html', 'name': 'Elewacje', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/materialy-wykonczeniowe/plyty-karton-gips-i-akcesoria,a218.html', 'name': 'Płyty karton-gips i akcesoria', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/materialy-wykonczeniowe/sufity-podwieszane,a221.html', 'name': 'Sufity podwieszane', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/materialy-wykonczeniowe/pustaki-szklane-luksfery-i-akcesoria,a1538.html', 'name': 'Pustaki szklane - luksfery i akcesoria', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/okna-i-drzwi/drzwi-zewnetrzne,a225.html', 'name': 'Drzwi zewnętrzne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/okna-i-drzwi/drzwi-wewnetrzne-i-oscieznice,a2260.html', 'name': 'Drzwi wewnętrzne i ościeżnice', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/okna-i-drzwi/okna-swietliki-i-wylazy-dachowe,a227.html', 'name': 'Okna, świetliki i wyłazy dachowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/okna-i-drzwi/parapety,a228.html', 'name': 'Parapety', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/okna-i-drzwi/akcesoria-do-okien,a236.html', 'name': 'Akcesoria do okien', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/okna-i-drzwi/akcesoria-do-drzwi-zewnetrznych,a232.html', 'name': 'Akcesoria do drzwi zewnętrznych', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/ogrodzenia-i-bramy/ogrodzenia-metalowe-systemowe,a241.html', 'name': 'Ogrodzenia metalowe systemowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/ogrodzenia-i-bramy/ogrodzenia-metalowe-panelowe,a3012.html', 'name': 'Ogrodzenia metalowe panelowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/ogrodzenia-i-bramy/ogrodzenia-drewniane-i-kompozytowe,a3171.html', 'name': 'Ogrodzenia drewniane i kompozytowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/ogrodzenia-i-bramy/siatki-ogrodzeniowe-i-akcesoria,a3020.html', 'name': 'Siatki ogrodzeniowe i akcesoria', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/ogrodzenia-i-bramy/ogrodzenia-budowlane-tymczasowe,a3195.html', 'name': 'Ogrodzenia budowlane tymczasowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/ogrodzenia-i-bramy/bramy-garazowe-i-akcesoria,a245.html', 'name': 'Bramy garażowe i akcesoria', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/ogrodzenia-i-bramy/skrzynki-pocztowe-na-listy,a251.html', 'name': 'Skrzynki pocztowe na listy', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/ogrodzenia-i-bramy/oznakowanie-informacyjne,a248.html', 'name': 'Oznakowanie informacyjne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/narzedzia-budowlane/drabiny-i-rusztowania,a282.html', 'name': 'Drabiny i rusztowania', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/narzedzia-budowlane/betoniarki-taczki-kastry-worki,a285.html', 'name': 'Betoniarki, taczki, kastry, worki', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/narzedzia-budowlane/maszyny-budowlane-i-przyczepki,a295.html', 'name': 'Maszyny budowlane i przyczepki', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/narzedzia-budowlane/narzedzia-reczne,a287.html', 'name': 'Narzędzia ręczne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/narzedzia-budowlane/narzedzia-glazurnicze,a290.html', 'name': 'Narzędzia glazurnicze', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/hydraulika/instalacje-wodne-i-gazowe,a269.html', 'name': 'Instalacje wodne i gazowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/hydraulika/akcesoria-doprowadzenia-wody,a270.html', 'name': 'Akcesoria doprowadzenia wody', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/hydraulika/akcesoria-doprowadzenia-gazu,a272.html', 'name': 'Akcesoria doprowadzenia gazu', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/hydraulika/kanalizacja-zewnetrzna,a274.html', 'name': 'Kanalizacja zewnętrzna', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/hydraulika/kanalizacja-wewnetrzna,a277.html', 'name': 'Kanalizacja wewnętrzna', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/hydraulika/narzedzia-hydrauliczne,a280.html', 'name': 'Narzędzia hydrauliczne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/elektronarzedzia/wiertarki-wkretarki-mloty-udarowe,a123.html', 'name': 'Wiertarki, wkrętarki, młoty udarowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/elektronarzedzia/wyrzynarki-pilarki-pily-szablaste-nozyce,a131.html', 'name': 'Wyrzynarki, pilarki, piły szablaste, nożyce', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/elektronarzedzia/szlifierki-polerki-strugi,a136.html', 'name': 'Szlifierki, polerki, strugi', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/elektronarzedzia/wiertla-bity-mieszadla,a149.html', 'name': 'Wiertła, bity, mieszadła', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/elektronarzedzia/materialy-scierne-i-szczotki-druciane-do-elektronarzedzi,a3052.html', 'name': 'Materiały ścierne i szczotki druciane do elektronarzędzi', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/elektronarzedzia/tarcze-brzeszczoty-frezy,a3077.html', 'name': 'Tarcze, brzeszczoty, frezy', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/elektronarzedzia/akcesoria-do-elektronarzedzi,a151.html', 'name': 'Akcesoria do elektronarzędzi', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/elektronarzedzia/systemy-elektronarzedzi-akumulatorowych,a3211.html', 'name': 'Systemy elektronarzędzi akumulatorowych', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/narzedzia-reczne/mlotki-wkretaki,a639.html', 'name': 'Młotki, wkrętaki', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/narzedzia-reczne/klucze-reczne,a2624.html', 'name': 'Klucze ręczne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/narzedzia-reczne/szczypce-pily-nozyce,a1527.html', 'name': 'Szczypce, piły, nożyce', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/narzedzia-reczne/miarki-katowniki-dalmierze,a732.html', 'name': 'Miarki, kątowniki, dalmierze', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/narzedzia-reczne/dluta-strugi-sciski,a743.html', 'name': 'Dłuta, strugi, ściski', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/narzedzia-reczne/pedzle-walki-kuwety,a752.html', 'name': 'Pędzle, wałki, kuwety', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/narzedzia-reczne/zszywacze-pistolety-klejowe-i-akcesoria,a770.html', 'name': 'Zszywacze, pistolety klejowe i akcesoria', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/narzedzia-reczne/materialy-scierne-szczotki-druciane,a795.html', 'name': 'Materiały ścierne, szczotki druciane', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/narzedzia-reczne/stoly-i-narzedzia-do-tapetowania,a3048.html', 'name': 'Stoły i narzędzia do tapetowania', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/warsztat/organizacja-warsztatu,a2198.html', 'name': 'Organizacja warsztatu', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/warsztat/wyposazenie-warsztatu,a830.html', 'name': 'Wyposażenie warsztatu', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/warsztat/urzadzenia-warsztatowe,a867.html', 'name': 'Urządzenia warsztatowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/warsztat/kompresory-i-urzadzenia-pneumatyczne,a893.html', 'name': 'Kompresory i urządzenia pneumatyczne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/warsztat/spawarki-i-akcesoria,a915.html', 'name': 'Spawarki i akcesoria', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/warsztat/akcesoria-samochodowe,a2934.html', 'name': 'Akcesoria samochodowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/warsztat/lutownice-i-akcesoria-lutownicze,a1524.html', 'name': 'Lutownice i akcesoria lutownicze', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/warsztat/palniki-gazowe-i-akcesoria,a1506.html', 'name': 'Palniki gazowe i akcesoria', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/warsztat/narzedzia-modelarskie,a1500.html', 'name': 'Narzędzia modelarskie', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/warsztat/chemia-warsztatowa,a964.html', 'name': 'Chemia warsztatowa', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/odziez-i-artykuly-bhp/odziez-i-obuwie-ochronne-bhp,a3135.html', 'name': 'Odzież i obuwie ochronne BHP', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/odziez-i-artykuly-bhp/okulary-maski-nauszniki-kaski-ochronne,a3136.html', 'name': 'Okulary, maski, nauszniki, kaski ochronne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/odziez-i-artykuly-bhp/apteczki-gasnice,a3152.html', 'name': 'Apteczki, gaśnice', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/odziez-i-artykuly-bhp/oznakowanie-bhp,a3137.html', 'name': 'Oznakowanie BHP', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/hydraulika/hydrofory-i-pompy,a979.html', 'name': 'Hydrofory i pompy', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/hydraulika/ogrzewacze-wody,a981.html', 'name': 'Ogrzewacze wody', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/hydraulika/uzdatnianie-wody,a983.html', 'name': 'Uzdatnianie wody', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/ogrzewanie/grzejniki-i-akcesoria,a1001.html', 'name': 'Grzejniki i akcesoria', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/ogrzewanie/kotly-i-piece,a1002.html', 'name': 'Kotły i piece', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/ogrzewanie/akcesoria-do-piecow,a1003.html', 'name': 'Akcesoria do pieców', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/ogrzewanie/ogrzewanie-elektryczne,a1004.html', 'name': 'Ogrzewanie elektryczne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/ogrzewanie/ogrzewanie-gazowe-i-naftowe,a1005.html', 'name': 'Ogrzewanie gazowe i naftowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/ogrzewanie/regulacja-temperatury,a1006.html', 'name': 'Regulacja temperatury', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/klimatyzacja-i-wentylacja/klimatyzatory-wentylatory-osuszacze,a1033.html', 'name': 'Klimatyzatory, wentylatory, osuszacze', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/klimatyzacja-i-wentylacja/instalacje-wentylacyjne,a1034.html', 'name': 'Instalacje wentylacyjne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/klimatyzacja-i-wentylacja/termometry-i-stacje-meteo,a1035.html', 'name': 'Termometry i stacje meteo', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/elektrycznosc/gniazda-wtyczki-akcesoria,a1051.html', 'name': 'Gniazda, wtyczki, akcesoria', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/elektrycznosc/instalacje-elektryczne,a1052.html', 'name': 'Instalacje elektryczne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/elektrycznosc/akcesoria-elektryczne,a1053.html', 'name': 'Akcesoria elektryczne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/elektrycznosc/osprzet-rtv-telefoniczny-i-komputerowy,a1054.html', 'name': 'Osprzęt RTV, telefoniczny i komputerowy', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/elektrycznosc/narzedzia-elektroinstalacyjne,a1055.html', 'name': 'Narzędzia elektroinstalacyjne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/elektrycznosc/baterie-ladowarki-latarki,a1084.html', 'name': 'Baterie, ładowarki, latarki', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/artykuly-metalowe/gwozdzie-wkrety-sruby,a1089.html', 'name': 'Gwoździe, wkręty, śruby', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/artykuly-metalowe/kolki-kotwy,a2222.html', 'name': 'Kołki, kotwy', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/artykuly-metalowe/nakretki-podkladki-zaslepki,a1090.html', 'name': 'Nakrętki, podkładki, zaślepki', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/artykuly-metalowe/lancuchy-liny-tasmy,a1091.html', 'name': 'Łańcuchy, liny, taśmy', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/artykuly-metalowe/profile-blachy-i-akcesoria,a1092.html', 'name': 'Profile, blachy i akcesoria', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/artykuly-metalowe/kolka-sprezyny,a1093.html', 'name': 'Kółka, sprężyny', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/artykuly-metalowe/haczyki-zawieszki-i-magnesy,a2191.html', 'name': 'Haczyki, zawieszki i magnesy', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/artykuly-metalowe/systemy-instalacyjne,a2194.html', 'name': 'Systemy instalacyjne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/zabezpieczenie-domu/zamki-do-drzwi-wkladki-klodki,a1117.html', 'name': 'Zamki do drzwi, wkładki, kłódki', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/zabezpieczenie-domu/dzwonki-gongi-domofony,a1118.html', 'name': 'Dzwonki, gongi, domofony', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/zabezpieczenie-domu/alarmy-monitoring,a1119.html', 'name': 'Alarmy, monitoring', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/zabezpieczenie-domu/systemy-smart-home,a3358.html', 'name': 'Systemy Smart Home', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/zabezpieczenie-domu/sejfy-kasetki-szafy-na-bron,a1120.html', 'name': 'Sejfy, kasetki, szafy na broń', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/farby-lakiery-i-kleje/srodki-i-farby-do-drewna,a1145.html', 'name': 'Środki i farby do drewna', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/farby-lakiery-i-kleje/farby-i-srodki-specjalistyczne,a1146.html', 'name': 'Farby i środki specjalistyczne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/farby-lakiery-i-kleje/rozpuszczalniki-rozcienczalniki,a1148.html', 'name': 'Rozpuszczalniki, rozcieńczalniki', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/farby-lakiery-i-kleje/kleje,a1147.html', 'name': 'Kleje', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/farby-lakiery-i-kleje/szpachlowki-i-akcesoria,a1641.html', 'name': 'Szpachlówki i akcesoria', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/artykuly-gospodarcze/tasmy-folie-ochronne,a1167.html', 'name': 'Taśmy, folie ochronne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/artykuly-gospodarcze/narzedzia-do-sprzatania,a1165.html', 'name': 'Narzędzia do sprzątania', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/artykuly-gospodarcze/srodki-czystosci,a1166.html', 'name': 'Środki czystości', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/drzwi-klamki-i-schody/drzwi-zewnetrzne,a2554.html', 'name': 'Drzwi zewnętrzne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/drzwi-klamki-i-schody/drzwi-i-oscieznice-wewnetrzne,a129.html', 'name': 'Drzwi i ościeżnice wewnętrzne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/drzwi-klamki-i-schody/klamki-i-galki-drzwiowe-wewnetrzne,a134.html', 'name': 'Klamki i gałki drzwiowe wewnętrzne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/drzwi-klamki-i-schody/klamki-i-galki-drzwiowe-zewnetrzne,a2559.html', 'name': 'Klamki i gałki drzwiowe zewnętrzne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/drzwi-klamki-i-schody/akcesoria-do-drzwi,a1833.html', 'name': 'Akcesoria do drzwi', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/drzwi-klamki-i-schody/schody-balustrady,a139.html', 'name': 'Schody, balustrady', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/drzwi-klamki-i-schody/oznakowanie-drzwi,a3328.html', 'name': 'Oznakowanie drzwi', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/podlogi-drewniane-panele-scienne/panele-deski-parkiety,a186.html', 'name': 'Panele, deski, parkiety', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/podlogi-drewniane-panele-scienne/listwy-i-akcesoria-wykonczeniowe,a194.html', 'name': 'Listwy i akcesoria wykończeniowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/podlogi-drewniane-panele-scienne/srodki-do-podlog-z-drewna,a212.html', 'name': 'Środki do podłóg z drewna', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/podlogi-drewniane-panele-scienne/panele-scienne-i-boazeria,a1550.html', 'name': 'Panele ścienne i boazeria', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/plytki-ceramiczne-na-sciane-i-podloge/plytki-ceramiczne,a229.html', 'name': 'Płytki ceramiczne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/plytki-ceramiczne-na-sciane-i-podloge/plytki-scienne,a2992.html', 'name': 'Płytki ścienne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/plytki-ceramiczne-na-sciane-i-podloge/plytki-podlogowe,a2525.html', 'name': 'Płytki podłogowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/plytki-ceramiczne-na-sciane-i-podloge/kamienie-naturalne,a2528.html', 'name': 'Kamienie naturalne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/plytki-ceramiczne-na-sciane-i-podloge/fugi-silikony-akryle,a517.html', 'name': 'Fugi, silikony, akryle', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/plytki-ceramiczne-na-sciane-i-podloge/listwy-wykonczeniowe-krzyzyki-drzwiczki-rewizyjne,a2366.html', 'name': 'Listwy wykończeniowe, krzyżyki, drzwiczki rewizyjne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/kuchnie/meble-kuchenne,a637.html', 'name': 'Meble kuchenne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/kuchnie/zlewozmywaki-i-akcesoria,a13.html', 'name': 'Zlewozmywaki i akcesoria', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/kuchnie/baterie-kuchenne-i-akcesoria,a670.html', 'name': 'Baterie kuchenne i akcesoria', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/kuchnie/blaty-kuchenne-i-akcesoria,a2675.html', 'name': 'Blaty kuchenne i akcesoria', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/kuchnie/sprzet-agd,a1816.html', 'name': 'Sprzęt AGD', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/kuchnie/okapy-kuchenne-i-wentylacja,a677.html', 'name': 'Okapy kuchenne i wentylacja', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/kuchnie/oswietlenie-kuchenne,a684.html', 'name': 'Oświetlenie kuchenne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/akcesoria-kuchenne/zarzadzanie-odpadami,a3493.html', 'name': 'Zarządzanie odpadami', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/akcesoria-kuchenne/akcesoria-do-zmywania,a3495.html', 'name': 'Akcesoria do zmywania', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/akcesoria-kuchenne/akcesoria-do-przygotowywania-potraw,a3500.html', 'name': 'Akcesoria do przygotowywania potraw', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/akcesoria-kuchenne/organizacja-i-przechowywanie-w-kuchni,a3501.html', 'name': 'Organizacja i przechowywanie w kuchni', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/akcesoria-kuchenne/dzbanki-filtrujace-i-saturatory,a3531.html', 'name': 'Dzbanki filtrujące i saturatory', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/jadalnia/stoly-i-krzesla,a3502.html', 'name': 'Stoły i krzesła', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/jadalnia/serwowanie-potraw-i-napojow,a3503.html', 'name': 'Serwowanie potraw i napojów', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/jadalnia/tekstylia-stolowe,a3504.html', 'name': 'Tekstylia stołowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/jadalnia/dekoracja-stolu,a3542.html', 'name': 'Dekoracja stołu', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/meble-lazienkowe-i-lustra/zestawy-i-elementy-mebli-lazienkowych,a527.html', 'name': 'Zestawy i elementy mebli łazienkowych', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/meble-lazienkowe-i-lustra/produkty-dla-niepelnosprawnych,a537.html', 'name': 'Produkty dla niepełnosprawnych', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/ceramika-lazienkowa/umywalki-i-akcesoria,a572.html', 'name': 'Umywalki i akcesoria', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/ceramika-lazienkowa/wc,a576.html', 'name': 'WC', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/ceramika-lazienkowa/pisuary-bidety,a585.html', 'name': 'Pisuary, bidety', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/ceramika-lazienkowa/stelaze-podtynkowe,a2544.html', 'name': 'Stelaże podtynkowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/wanny-i-kabiny-prysznicowe/wanny-i-akcesoria,a2107.html', 'name': 'Wanny i akcesoria', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/wanny-i-kabiny-prysznicowe/kabiny-brodziki-i-akcesoria,a2108.html', 'name': 'Kabiny, brodziki i akcesoria', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/wanny-i-kabiny-prysznicowe/drazki-i-zaslonki-prysznicowe,a2147.html', 'name': 'Drążki i zasłonki prysznicowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/armatura-lazienkowa/baterie-lazienkowe,a591.html', 'name': 'Baterie łazienkowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/armatura-lazienkowa/natryski-hydroterapia,a597.html', 'name': 'Natryski, hydroterapia', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/armatura-lazienkowa/akcesoria-do-armatury,a2051.html', 'name': 'Akcesoria do armatury', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/wyposazenie-lazienki/ogrzewanie-wentylacja,a605.html', 'name': 'Ogrzewanie, wentylacja', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/wyposazenie-lazienki/oswietlenie-lazienkowe,a610.html', 'name': 'Oświetlenie łazienkowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/akcesoria-lazienkowe/dozowniki-mydelniczki-dystrybutory,a2094.html', 'name': 'Dozowniki, mydelniczki, dystrybutory', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/akcesoria-lazienkowe/dywaniki-i-maty-lazienkowe,a2095.html', 'name': 'Dywaniki i maty łazienkowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/akcesoria-lazienkowe/kosze-pojemniki-wagi-lazienkowe,a2133.html', 'name': 'Kosze, pojemniki, wagi łazienkowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/akcesoria-lazienkowe/akcesoria-do-prania,a2139.html', 'name': 'Akcesoria do prania', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/akcesoria-lazienkowe/przechowywanie-w-lazience,a2695.html', 'name': 'Przechowywanie w łazience', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/akcesoria-lazienkowe/akcesoria-lazienkowe-dla-dzieci,a2699.html', 'name': 'Akcesoria łazienkowe dla dzieci', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/garderoba-i-wnetrze/elementy-zabudowy-garderoby-i-wnek,a726.html', 'name': 'Elementy zabudowy garderoby i wnęk', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/garderoba-i-wnetrze/meble,a786.html', 'name': 'Meble', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/garderoba-i-wnetrze/wieszaki-haki,a803.html', 'name': 'Wieszaki, haki', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/garderoba-i-wnetrze/pojemniki-pokrowce,a821.html', 'name': 'Pojemniki, pokrowce', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/garderoba-i-wnetrze/akcesoria-uzytkowe-i-produkty-do-przeprowadzki,a825.html', 'name': 'Akcesoria użytkowe i produkty do przeprowadzki', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/elementy-mebli-i-okucia/polki-i-wsporniki,a2616.html', 'name': 'Półki i wsporniki', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/elementy-mebli-i-okucia/plyty-wykonczeniowe,a835.html', 'name': 'Płyty wykończeniowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/elementy-mebli-i-okucia/galki-uchwyty-klucze,a849.html', 'name': 'Gałki, uchwyty, klucze', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/elementy-mebli-i-okucia/okucia-i-zlacza-meblowe,a857.html', 'name': 'Okucia i złącza meblowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/elementy-mebli-i-okucia/akcesoria-meblowe,a880.html', 'name': 'Akcesoria meblowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/kominki/kominki-piece-kominkowe,a897.html', 'name': 'Kominki, piece kominkowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/kominki/instalacje-kominkowe,a909.html', 'name': 'Instalacje kominkowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/kominki/akcesoria-i-materialy-eksploatacyjne,a923.html', 'name': 'Akcesoria i materiały eksploatacyjne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/farby/farby-do-scian-i-sufitow,a740.html', 'name': 'Farby do ścian i sufitów', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/farby/efekty-dekoratorskie,a767.html', 'name': 'Efekty dekoratorskie', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/farby/emalie-spraye,a808.html', 'name': 'Emalie, spraye', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/farby/srodki-do-drewna,a813.html', 'name': 'Środki do drewna', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/farby/przygotowanie-podloza,a848.html', 'name': 'Przygotowanie podłoża', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/farby/walki-pedzle-akcesoria-malarskie,a3183.html', 'name': 'Wałki, pędzle, akcesoria malarskie', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/dekoracja-scian-sufitow-i-innych-powierzchni/tapety-bordiury,a866.html', 'name': 'Tapety, bordiury', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/dekoracja-scian-sufitow-i-innych-powierzchni/fototapety-naklejki,a903.html', 'name': 'Fototapety, naklejki', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/dekoracja-scian-sufitow-i-innych-powierzchni/kleje-i-akcesoria-do-tapetowania,a910.html', 'name': 'Kleje i akcesoria do tapetowania', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/dekoracja-scian-sufitow-i-innych-powierzchni/okleiny-meblowe-folie-statyczne-akcesoria,a2652.html', 'name': 'Okleiny meblowe, folie statyczne, akcesoria', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/dekoracja-scian-sufitow-i-innych-powierzchni/sztukateria-dekoracja-sufitu,a914.html', 'name': 'Sztukateria, dekoracja sufitu', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/dekoracja-okien/tkaniny-firany-i-akcesoria,a942.html', 'name': 'Tkaniny, firany i akcesoria', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/dekoracja-okien/karnisze,a933.html', 'name': 'Karnisze', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/dekoracja-okien/szyny-i-akcesoria,a1324.html', 'name': 'Szyny i akcesoria', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/dekoracja-okien/rolety-i-zaluzje,a927.html', 'name': 'Rolety i żaluzje', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/dekoracja-okien/pasmanteria,a949.html', 'name': 'Pasmanteria', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/oswietlenie/oswietlenie-scienne-i-sufitowe,a954.html', 'name': 'Oświetlenie ścienne i sufitowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/oswietlenie/oswietlenie-podlogowe,a3219.html', 'name': 'Oświetlenie podłogowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/oswietlenie/oswietlenie-stolowe-biurkowe,a978.html', 'name': 'Oświetlenie stołowe, biurkowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/oswietlenie/reflektory-i-halogeny-sufitowe,a972.html', 'name': 'Reflektory i halogeny sufitowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/oswietlenie/panele-led-oswietlenie-funkcjonalne,a3030.html', 'name': 'Panele LED, oświetlenie funkcjonalne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/oswietlenie/oswietlenie-do-kuchni,a3032.html', 'name': 'Oświetlenie do kuchni', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/oswietlenie/oswietlenie-do-lazienki,a2507.html', 'name': 'Oświetlenie do łazienki', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/oswietlenie/stworz-wlasna-lampe,a992.html', 'name': 'Stwórz własną lampę', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/oswietlenie/tasmy-led-profile-zasilacze,a1185.html', 'name': 'Taśmy LED, profile, zasilacze', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/oswietlenie/zarowki-led-swietlowki,a2447.html', 'name': 'Żarówki LED, świetlówki', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/oswietlenie/akcesoria-i-osprzet-oswietleniowy,a2455.html', 'name': 'Akcesoria i osprzęt oświetleniowy', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/oswietlenie/oswietlenie-ogrodowe,a2736.html', 'name': 'Oświetlenie ogrodowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/dywany-i-wykladziny/dywany,a1211.html', 'name': 'Dywany', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/dywany-i-wykladziny/wykladziny-podlogowe-sztuczne-trawy,a1216.html', 'name': 'Wykładziny podłogowe, sztuczne trawy', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/dywany-i-wykladziny/chodniki-i-nakladki-schodowe,a1221.html', 'name': 'Chodniki i nakładki schodowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/dywany-i-wykladziny/wycieraczki-zewnetrzne-i-wewnetrzne,a1224.html', 'name': 'Wycieraczki zewnętrzne i wewnętrzne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/dekoracja-wnetrz/swiece-olejki-zapachowe-swieczniki,a3104.html', 'name': 'Świece, olejki zapachowe, świeczniki', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/dekoracja-wnetrz/poduszki-siedziska-narzuty-posciel-legowiska,a1235.html', 'name': 'Poduszki, siedziska, narzuty, pościel, legowiska', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/dekoracja-wnetrz/dekoracja-stolu,a3105.html', 'name': 'Dekoracja stołu', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/dekoracja-wnetrz/artykuly-dekoracyjne,a1246.html', 'name': 'Artykuły dekoracyjne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/dekoracja-wnetrz/swiat-dziecka,a3288.html', 'name': 'Świat dziecka', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/dekoracja-wnetrz/dekoracje-i-ozdoby-swiateczne,a1256.html', 'name': 'Dekoracje i ozdoby świąteczne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/ramki-obrazy-lustra/ramki-galerie-antyramy,a1293.html', 'name': 'Ramki, galerie, antyramy', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/ramki-obrazy-lustra/obrazy-plakaty-i-dekoracje-scienne,a1294.html', 'name': 'Obrazy, plakaty i dekoracje ścienne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/ramki-obrazy-lustra/lustra,a1296.html', 'name': 'Lustra', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/atelier-artystyczne/artykuly-dla-plastykow,a1309.html', 'name': 'Artykuły dla plastyków', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/atelier-artystyczne/artykuly-dla-dzieci,a1314.html', 'name': 'Artykuły dla dzieci', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/organizacja-miejsca-pracy/tablice-kredowe-i-korkowe,a2491.html', 'name': 'Tablice kredowe i korkowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/organizacja-miejsca-pracy/akcesoria-biurowe,a2497.html', 'name': 'Akcesoria biurowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/organizacja-miejsca-pracy/oswietlenie-miejsca-pracy,a2517.html', 'name': 'Oświetlenie miejsca pracy', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/maszyny-ogrodnicze/kosiarki-traktorki-roboty-koszace,a28.html', 'name': 'Kosiarki, traktorki, roboty koszące', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/maszyny-ogrodnicze/kosy-podkaszarki,a3200.html', 'name': 'Kosy, podkaszarki', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/maszyny-ogrodnicze/wertykulatory-glebogryzarki,a29.html', 'name': 'Wertykulatory, glebogryzarki', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/maszyny-ogrodnicze/pily-pilarki-luparki,a30.html', 'name': 'Piły, pilarki, łuparki', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/maszyny-ogrodnicze/nozyce-ogrodowe,a1576.html', 'name': 'Nożyce ogrodowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/maszyny-ogrodnicze/oleje-filtry-swiece-zaplonowe,a31.html', 'name': 'Oleje, filtry, świece zapłonowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/maszyny-ogrodnicze/przedluzacze-ladowarki-akumulatory,a32.html', 'name': 'Przedłużacze, ładowarki, akumulatory', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/porzadki-w-ogrodzie/myjki-i-akcesoria,a33.html', 'name': 'Myjki i akcesoria', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/porzadki-w-ogrodzie/odkurzacze-rozdrabniacze,a34.html', 'name': 'Odkurzacze, rozdrabniacze', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/porzadki-w-ogrodzie/zamiatarki-odsniezarki-lopaty,a36.html', 'name': 'Zamiatarki, odśnieżarki, łopaty', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/porzadki-w-ogrodzie/gospodarka-odpadami-segregacja-smieci,a35.html', 'name': 'Gospodarka odpadami, segregacja śmieci', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/porzadki-w-ogrodzie/transport-i-przechowywanie,a2582.html', 'name': 'Transport i przechowywanie', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/porzadki-w-ogrodzie/szczotki-grabie-srodki-czystosci,a37.html', 'name': 'Szczotki, grabie, środki czystości', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/porzadki-w-ogrodzie/suszarki-ogrodowe-i-akcesoria,a38.html', 'name': 'Suszarki ogrodowe i akcesoria', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/narzedzia-ogrodnicze/nozyce-sekatory,a39.html', 'name': 'Nożyce, sekatory', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/narzedzia-ogrodnicze/siekiery-pily-noze,a40.html', 'name': 'Siekiery, piły, noże', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/narzedzia-ogrodnicze/prace-w-ziemi,a41.html', 'name': 'Prace w ziemi', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/narzedzia-ogrodnicze/pielegnacja-trawnika-i-roslin,a2156.html', 'name': 'Pielęgnacja trawnika i roślin', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/narzedzia-ogrodnicze/serie-narzedzi-i-narzedzia-drobne,a42.html', 'name': 'Serie narzędzi i narzędzia drobne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/narzedzia-ogrodnicze/odziez-robocza,a43.html', 'name': 'Odzież robocza', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/narzedzia-ogrodnicze/akcesoria-do-narzedzi,a1719.html', 'name': 'Akcesoria do narzędzi', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/nawadnianie/pompy-i-hydrofory,a1824.html', 'name': 'Pompy i hydrofory', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/nawadnianie/weze-zlaczki-zraszacze,a1698.html', 'name': 'Węże, złączki, zraszacze', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/nawadnianie/zbiorniki-na-deszczowke-konewki,a54.html', 'name': 'Zbiorniki na deszczówkę, konewki', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/nawadnianie/nawadnianie-wynurzalne,a53.html', 'name': 'Nawadnianie wynurzalne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/nawadnianie/nawadnianie-kropelkowe,a52.html', 'name': 'Nawadnianie kropelkowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/nawadnianie/automatyka-do-nawadniania,a1691.html', 'name': 'Automatyka do nawadniania', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/relaks-w-ogrodzie/grille-i-akcesoria,a44.html', 'name': 'Grille i akcesoria', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/relaks-w-ogrodzie/meble-ogrodowe,a45.html', 'name': 'Meble ogrodowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/relaks-w-ogrodzie/parasole-pawilony-markizy,a46.html', 'name': 'Parasole, pawilony, markizy', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/relaks-w-ogrodzie/hustawki-ogrodowe-hamaki,a47.html', 'name': 'Huśtawki ogrodowe, hamaki', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/relaks-w-ogrodzie/baseny-i-akcesoria,a1916.html', 'name': 'Baseny i akcesoria', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/relaks-w-ogrodzie/plac-zabaw-dla-dzieci,a48.html', 'name': 'Plac zabaw dla dzieci', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/relaks-w-ogrodzie/ochrona-przed-owadami,a49.html', 'name': 'Ochrona przed owadami', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/relaks-w-ogrodzie/camping-biwak,a2434.html', 'name': 'Camping, biwak', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/architektura-ogrodowa/tarasy-sciezki-podjazdy,a55.html', 'name': 'Tarasy, ścieżki, podjazdy', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/architektura-ogrodowa/domki-altany-i-wiaty,a1912.html', 'name': 'Domki, altany i wiaty', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/architektura-ogrodowa/ploty-pergole-kratki-donice-ogrodowe,a56.html', 'name': 'Płoty, pergole, kratki, donice ogrodowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/architektura-ogrodowa/oczka-wodne,a58.html', 'name': 'Oczka wodne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/architektura-ogrodowa/budy-karmniki-karma-dla-ptakow,a2239.html', 'name': 'Budy, karmniki, karma dla ptaków', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/oswietlenie-doniczki-i-dekoracje/oswietlenie-ogrodowe-i-zewnetrzne,a61.html', 'name': 'Oświetlenie ogrodowe i zewnętrzne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/oswietlenie-doniczki-i-dekoracje/doniczki-oslonki-i-kwietniki,a62.html', 'name': 'Doniczki, osłonki i kwietniki', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/oswietlenie-doniczki-i-dekoracje/donice-ogrodowe-i-skrzynki-balkonowe,a63.html', 'name': 'Donice ogrodowe i skrzynki balkonowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/oswietlenie-doniczki-i-dekoracje/oslony-na-balkon,a1950.html', 'name': 'Osłony na balkon', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/oswietlenie-doniczki-i-dekoracje/lampiony-figury-i-fontanny,a1921.html', 'name': 'Lampiony, figury i fontanny', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/oswietlenie-doniczki-i-dekoracje/dodatki-dekoracyjne,a1631.html', 'name': 'Dodatki dekoracyjne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/balkon-i-taras/markizy-maty-oslony,a2383.html', 'name': 'Markizy, maty, osłony', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/balkon-i-taras/meble-tarasowe-i-balkonowe,a2375.html', 'name': 'Meble tarasowe i balkonowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/balkon-i-taras/plytki-deski-i-podesty-tarasowe,a2369.html', 'name': 'Płytki, deski i podesty tarasowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/balkon-i-taras/oswietlenie-balkonu-i-tarasu,a2417.html', 'name': 'Oświetlenie balkonu i tarasu', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/balkon-i-taras/doniczki-oslonki-kwietniki,a2389.html', 'name': 'Doniczki, osłonki, kwietniki', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/balkon-i-taras/skrzynki-balkonowe-donice,a2395.html', 'name': 'Skrzynki balkonowe, donice', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/balkon-i-taras/dekoracje-i-ozdoby,a2401.html', 'name': 'Dekoracje i ozdoby', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/balkon-i-taras/rosliny-na-balkon,a2405.html', 'name': 'Rośliny na balkon', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/balkon-i-taras/podlewanie,a2409.html', 'name': 'Podlewanie', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/rosliny-nasiona-cebule/kwiaty-doniczkowe-i-pokojowe,a3367.html', 'name': 'Kwiaty doniczkowe i pokojowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/rosliny-nasiona-cebule/rosliny-balkonowe-i-ogrodowe,a64.html', 'name': 'Rośliny balkonowe i ogrodowe', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/rosliny-nasiona-cebule/las-w-sloiku,a3303.html', 'name': 'Las w słoiku', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/rosliny-nasiona-cebule/obrazy-z-mchu-zielone-sciany,a3383.html', 'name': 'Obrazy z mchu, zielone ściany', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/rosliny-nasiona-cebule/trawa,a3044.html', 'name': 'Trawa', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/rosliny-nasiona-cebule/nasiona-i-grzybnie,a65.html', 'name': 'Nasiona i grzybnie', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/rosliny-nasiona-cebule/cebulki,a66.html', 'name': 'Cebulki', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/uprawa-i-ochrona-roslin/podloza-nawozy,a67.html', 'name': 'Podłoża, nawozy', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/uprawa-i-ochrona-roslin/srodki-ochrony-roslin-opryskiwacze,a68.html', 'name': 'Środki ochrony roślin, opryskiwacze', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/uprawa-i-ochrona-roslin/szklarnie-tunele-kompostowniki,a2209.html', 'name': 'Szklarnie, tunele, kompostowniki', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/uprawa-i-ochrona-roslin/podporki-paletki-do-rozsad,a69.html', 'name': 'Podpórki, paletki do rozsad', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/uprawa-i-ochrona-roslin/agrowlokniny-folie-siatki-ochronne,a70.html', 'name': 'Agrowłókniny, folie, siatki ochronne', 'has_childs': True, 'has_products': False},
{'url': 'https://www.leroymerlin.pl/uprawa-i-ochrona-roslin/przetworstwo-warzyw-i-owocow,a72.html', 'name': 'Przetwórstwo warzyw i owoców', 'has_childs': True, 'has_products': False},
]

scraper = LeroyMerlinScraper(
    requested_url="https://www.leroymerlin.pl/",
    store_url="https://www.leroymerlin.pl/"
)

# # Find CATEGORIES lvl 2
# for dict in url_2:
#     element = scraper.visit_page(url=dict['url'])
#     generator = scraper.find_category_data(category_level=2, html_element=element)
#     with open("manual_url.txt", "a") as myfile:
#         for cat in generator:
#             myfile.write(f"{str(cat)},\n")
#     scraper.quit_and_clean()


# Find CATEGORIES lvl 3
print('!!!!! STARTING CATS 3  !!!!!')
for dict in url_3:
    print(dict['url'])
    element = scraper.visit_page(url=dict['url'])
    generator = scraper.find_category_data(category_level=3, html_element=element)
    with open("manual_url.txt", "a") as myfile:
        for cat in generator:
            myfile.write(f"{str(cat)},\n")
    scraper.quit_and_clean()
