# Generated by Django 4.2.1 on 2023-05-17 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcommerceStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('discovery_url', models.CharField(max_length=100, unique=True)),
                ('api_url', models.URLField(blank=True, max_length=255)),
                ('package_name', models.CharField(blank=True, max_length=50)),
                ('module_name', models.CharField(blank=True, max_length=50)),
                ('class_name', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ACTIVE', 'Picked Up'), ('FAILED', 'Extended'), ('FINISHED', 'Finished')], default='CREATED', max_length=10)),
                ('created', models.IntegerField()),
                ('started_at', models.IntegerField(blank=True, null=True)),
                ('finished_at', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('PRODUCT SCRAPE', 'Product Scrape')], default='PRODUCT SCRAPE', max_length=30)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='objects.ecommercestore')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScrapeLocalProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ACTIVE', 'Picked Up'), ('FAILED', 'Extended'), ('FINISHED', 'Finished')], default='CREATED', max_length=10)),
                ('created', models.IntegerField()),
                ('started_at', models.IntegerField(blank=True, null=True)),
                ('finished_at', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('PRODUCT LOCAL DATA SCRAPE', 'Product Local Scrape')], default='PRODUCT LOCAL DATA SCRAPE', max_length=45)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='objects.ecommercestore')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocalStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField(blank=True, max_length=255)),
                ('api_url', models.URLField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('parrent_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.ecommercestore')),
            ],
        ),
        migrations.CreateModel(
            name='CrawlProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ACTIVE', 'Picked Up'), ('FAILED', 'Extended'), ('FINISHED', 'Finished')], default='CREATED', max_length=10)),
                ('created', models.IntegerField()),
                ('started_at', models.IntegerField(blank=True, null=True)),
                ('finished_at', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('PRODUCTS CRAWL', 'Products Crawl')], default='PRODUCTS CRAWL', max_length=30)),
                ('category_level', models.IntegerField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='objects.ecommercestore')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CrawlLocalStores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ACTIVE', 'Picked Up'), ('FAILED', 'Extended'), ('FINISHED', 'Finished')], default='CREATED', max_length=10)),
                ('created', models.IntegerField()),
                ('started_at', models.IntegerField(blank=True, null=True)),
                ('finished_at', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('STORES CRAWL', 'Stores Crawl')], default='STORES CRAWL', max_length=30)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='objects.ecommercestore')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CrawlCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ACTIVE', 'Picked Up'), ('FAILED', 'Extended'), ('FINISHED', 'Finished')], default='CREATED', max_length=10)),
                ('created', models.IntegerField()),
                ('started_at', models.IntegerField(blank=True, null=True)),
                ('finished_at', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('CATEGORIES CRAWL', 'Categories Crawl')], default='CATEGORIES CRAWL', max_length=30)),
                ('category_level', models.IntegerField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='objects.ecommercestore')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
